import { Card } from './Card.jsx';
import { timeAgo } from '../lib/format.js';

const Section = ({ title, items }) =>
  items.length > 0 && (
    <div className="mt-4">
      <h3 className="text-xs font-semibold uppercase tracking-wide text-slate-500">{title}</h3>
      <ul className="mt-1.5 list-disc space-y-1 pl-5 text-sm text-slate-700">
        {items.map((t) => <li key={t}>{t}</li>)}
      </ul>
    </div>
  );

export default function AiSummary({ report, generating, error, onGenerate }) {
  return (
    <Card
      title="AI sprint summary"
      action={
        <button
          onClick={onGenerate}
          disabled={generating}
          className="rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-indigo-500 disabled:opacity-60"
        >
          {generating ? 'Generating...' : report ? 'Regenerate' : 'Generate'}
        </button>
      }
    >
      {error && <p role="alert" className="mb-3 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}
      {!report ? (
        <p className="py-6 text-center text-sm text-slate-400">
          Generate a sprint summary, productivity insights and suggestions for this period.
        </p>
      ) : (
        <>
          <p className="text-sm leading-relaxed text-slate-800">{report.content.summary}</p>
          <Section title="Productivity insights" items={report.content.insights} />
          <Section title="Suggestions" items={report.content.suggestions} />
          <p className="mt-4 text-xs text-slate-400">
            {report.provider === 'local' ? 'Rule-based summary (no AI key configured)' : `Generated by ${report.provider}`}
            {' '}- last {report.days} days - {timeAgo(report.createdAt)}
          </p>
        </>
      )}
    </Card>
  );
}
