import { Copy, Sparkles } from 'lucide-react';
import { toast } from 'sonner';
import { Card, CardBody, CardHeader } from '../ui/Card.jsx';
import { Badge } from '../ui/Badge.jsx';
import { Button } from '../ui/Button.jsx';
import { Skeleton } from '../ui/Skeleton.jsx';
import { EmptyState } from '../ui/States.jsx';
import { timeAgo } from '../../lib/format.js';
import { cn } from '../../lib/cn.js';

const toMarkdown = (r) => [
  `## Sprint summary`, '', r.content.summary, '',
  '### Productivity insights', ...r.content.insights.map((i) => `- ${i}`), '',
  '### Suggestions', ...r.content.suggestions.map((s) => `- ${s}`),
].join('\n');

function Section({ title, items, start }) {
  if (!items.length) return null;
  return (
    <div className="mt-5">
      <h3 className="text-xs font-semibold uppercase tracking-wider text-fg-muted">{title}</h3>
      <ul className="mt-2 space-y-2">
        {items.map((t, i) => (
          <li key={t} className="rise flex gap-2.5 text-[13px] leading-relaxed" style={{ '--i': start + i }}>
            <span className="mt-[9px] h-1 w-1 shrink-0 rounded-full bg-fg-faint" aria-hidden="true" />
            <span>{t}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

export function AiReport({ report, generating, onGenerate, compact = false, className, footer }) {
  const copy = async () => {
    try { await navigator.clipboard.writeText(toMarkdown(report)); toast.success('Copied as Markdown'); }
    catch { toast.error('Could not copy to the clipboard'); }
  };
  const local = report?.provider === 'local';

  return (
    <Card className={cn('h-full', className)}>
      <CardHeader
        title={<span className="inline-flex items-center gap-2"><Sparkles size={15} className="text-accent" aria-hidden="true" /> AI sprint summary</span>}
        description={report ? `Last ${report.days} days · ${timeAgo(report.createdAt)}` : 'Written from your repository metrics'}
        actions={(
          <>
            {report && !compact && <Button size="sm" variant="ghost" icon={Copy} onClick={copy}>Copy</Button>}
            <Button size="sm" variant="primary" loading={generating} onClick={onGenerate}>{report ? 'Regenerate' : 'Generate'}</Button>
          </>
        )}
      />
      <CardBody>
        {generating && !report ? (
          <div className="space-y-2.5" aria-busy="true" aria-label="Generating summary">
            <Skeleton className="h-3.5 w-full" /><Skeleton className="h-3.5 w-11/12" /><Skeleton className="h-3.5 w-2/3" />
          </div>
        ) : !report ? (
          <EmptyState icon={Sparkles} title="No summary yet" className="py-8">
            Generate a sprint summary with insights and suggestions for the selected period.
          </EmptyState>
        ) : (
          <div key={report.id} className={cn(generating && 'swap')} data-pending={generating}>
            <p className="fade-in text-sm leading-relaxed">{report.content.summary}</p>
            <Section title="Productivity insights" items={report.content.insights.slice(0, compact ? 3 : 8)} start={1} />
            <Section title="Suggestions" items={report.content.suggestions.slice(0, compact ? 2 : 8)} start={5} />
            <div className="mt-5 flex flex-wrap items-center gap-2">
              <Badge tone={local ? 'neutral' : 'accent'}>{local ? 'Rule-based' : `Generated by ${report.provider}`}</Badge>
              {report.model && <span className="mono text-[11px] text-fg-faint">{report.model}</span>}
              {local && <span className="text-xs text-fg-faint">Add an AI key to get model-written summaries.</span>}
            </div>
          </div>
        )}
        {footer}
      </CardBody>
    </Card>
  );
}
